---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: russellhost # change to your domain
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: russellhost-tls # change to your secretname
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.russellhost.org" # change to your domain
  dnsNames:
  - "*.russellhost.org" # change to your domain
  - russellhost.org # change to your domain
