---
version: "3.6"

networks:
  media-network:
    name: media-network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "${DOCKER_SUBNET:?err}"
        gateway: "${DOCKER_GATEWAY:?err}"

services:
  gluetun:
    container_name: "gluetun"
    image: "qmcgaw/gluetun:latest"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - "PUID=0"
      - "VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:?err}"
      - "OPENVPN_USER=${VPN_USERNAME:?err}"
      - "OPENVPN_PASSWORD=${VPN_PASSWORD:?err}"
      - "SERVER_REGIONS=United States"
      - "VPN_TYPE=${VPN_TYPE:?err}"
      - "VPN_INTERFACE=tun0"
      - "OPENVPN_PROTOCOL=udp"
      - "HTTPPROXY_LISTENING_ADDRESS=:8888"
    networks:
      - "media-network"
    ports:
      - "8888:8888/tcp"                         # Gluetun Local Network HTTP proxy
      - "8388:8388/tcp"                         # Gluetun Local Network Shadowsocks
      - "8388:8388/udp"                         # Gluetun Local Network Shadowsocks
      - "${WEBUI_PORT_QBITTORRENT:?err}:${WEBUI_PORT_QBITTORRENT:?err}"   # WebUI Portal: qBittorrent
    restart: "always"

  QbitTorrent-Nord:
    container_name: "QbitTorrent-Nord"
    environment:
      - "TZ=${TIMEZONE:?err}"
      - "WEBUI_PORT=${WEBUI_PORT_QBITTORRENT:?err}"
      - "PUID=${PUID:?err}"
      - "PGID=${PGID:?err}"
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=${TP_THEME:?err}
    image: "linuxserver/qbittorrent:latest"
    restart: "always"
    volumes:
      - "${FOLDER_FOR_CONFIGS:?err}/qbit:/config"
      - "${FOLDER_FOR_MEDIA:?err}/downloads:/downloads"
    network_mode: "service:gluetun"

  jackett:
    container_name: "jackett"
    environment:
      - "PUID=${PUID:?err}"
      - "PGID=${PGID:?err}"
      - "TZ=${TIMEZONE:?err}"
      - "AUTO_UPDATE=true"
    image: "lscr.io/linuxserver/jackett:latest"
    ports:
      - "${WEBUI_PORT_JACKETT:?err}:9117/tcp"
    restart: "unless-stopped"
    volumes:
      - "${FOLDER_FOR_MEDIA:?err}/blackhole:/downloads"
      - "${FOLDER_FOR_CONFIGS:?err}/jackett:/config"
    networks:
      - "media-network"

  radarr:
    container_name: "radarr"
    environment:
      - "PUID=${PUID:?err}"
      - "PGID=${PGID:?err}"
      - "TZ=${TIMEZONE:?err}"
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=${TP_THEME:?err}
    image: "linuxserver/radarr:latest"
    ports:
      - "${WEBUI_PORT_RADARR:?err}:7878/tcp"
    restart: "unless-stopped"
    volumes:
      - "${FOLDER_FOR_MEDIA:?err}/downloads:/downloads"
      - "${FOLDER_FOR_MEDIA:?err}/movies:/movies"
      - "${FOLDER_FOR_CONFIGS:?err}/radarr:/config"
    networks:
      - "media-network"

  sonarr:
    container_name: "sonarr"
    environment:
      - "PUID=${PUID:?err}"
      - "PGID=${PGID:?err}"
      - "TZ=${TIMEZONE:?err}"
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=${TP_THEME:?err}
    image: "linuxserver/sonarr:latest"
    ports:
      - "${WEBUI_PORT_SONARR:?err}:8989/tcp"
    restart: "unless-stopped"
    volumes:
      - "${FOLDER_FOR_MEDIA:?err}/downloads:/downloads"
      - "${FOLDER_FOR_MEDIA:?err}/tv:/tv"
      - "${FOLDER_FOR_CONFIGS:?err}/sonarr:/config"
    networks:
      - "media-network"

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/tdarr/server:/app/server
      - ${FOLDER_FOR_CONFIGS:?err}/tdarr/configs:/app/configs
      - ${FOLDER_FOR_CONFIGS:?err}/tdarr/logs:/app/logs
      - ${FOLDER_FOR_MEDIA:?err}/media/tdarr_transcode_cache:/temp
      - ${FOLDER_FOR_MEDIA:?err}:/data
    ports:
      - "${TDARR_SERVER_PORT:?err}:${TDARR_SERVER_PORT:?err}"
      - "${WEBUI_PORT_TDARR:?err}:${WEBUI_PORT_TDARR:?err}"
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - serverIP=0.0.0.0
      - serverPort=${TDARR_SERVER_PORT:?err}
      - webUIPort=${WEBUI_PORT_TDARR:?err}
      - internalNode=true
      - nodeID=Tdarr_Server
    networks:
      - media-network

  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/tdarr/configs:/app/configs
      - ${FOLDER_FOR_CONFIGS:?err}/tdarr/logs:/app/logs
      - ${FOLDER_FOR_MEDIA:?err}/media/tdarr_transcode_cache:/temp
      - ${FOLDER_FOR_MEDIA:?err}:/data
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - nodeID=Tdarr_Node_1
      - serverIP=0.0.0.0
      - serverPort=${TDARR_SERVER_PORT:?err}
    networks:
      - media-network
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
# Add Configurations for GPU Hardware Rendering Here:
#    devices:
#      - /dev/dri/renderD128:/dev/dri/renderD128
#      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/jellyfin:/config
      - ${FOLDER_FOR_MEDIA:?err}/media:/data/media
    ports:
      - "${WEBUI_PORT_JELLYFIN:?err}:8096"
#      - 7359:7359/udp      # Enable for DLNA - Only works on HOST Network Mode
#      - 1900:1900/udp      # Enable for DLNA - Only works on HOST Network Mode
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
#      - JELLYFIN_PublishedServerUrl=${LOCAL_DOCKER_IP:?err}  # Enable for DLNA - Only works on HOST Network Mode
    networks:
      - media-network

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/jellyseerr:/app/config
    ports:
      - "${WEBUI_PORT_JELLYSEERR:?err}:5055"
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
    networks:
      - media-network

  uptime-kuma:
    command:
      - "node"
      - "server/server.js"
    container_name: "uptime-kuma"
    entrypoint:
      - "/usr/bin/dumb-init"
      - "--"
      - "extra/entrypoint.sh"
    environment:
      - "PUID=${PUID:?err}"
      - "PGID=${PGID:?err}"
      - "UPTIME_KUMA_IS_CONTAINER=1"
    image: "louislam/uptime-kuma:1"
    ports:
      - "${WEBUI_PORT_UPTIMEKUMA:?err}:3001/tcp"
    restart: "always"
    volumes:
      - "${FOLDER_FOR_CONFIGS:?err}/uptimekuma:/app/data"
      - "${FOLDER_FOR_MEDIA:?err}/uptimekuma:/docker/data"
    working_dir: "/app"
    networks:
      - "media-network"
