- name: create ansible user
  user:
    name: ansible
    groups: root

- name: add ssh key for ansible
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINSi+y9JJj14bgwxhiRmO6CZVx2Hxl5TK+yYXLlP8DqW ansible"

- name: add sudoers file for ansible
  copy: 
    src: ./files/sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: update apt repos
  become: true
  apt:
    update_cache: yes
  changed_when: false

- name: install base packages
  become: true
  apt:
    name: "{{ base_packages }}"

- name: install host specific packages
  become: true
  apt:
    name: "{{ additional_packages }}"
  when: additional_packages is defined

- name: check if system reboot is required
  become: true
  stat:
    path: /var/run/reboot-required
  register: reboot_required

    # Send Discord message when reboot is required
- name: Send Discord message
  uri:
    url: "{{ discord_webhook_url }}"
    method: POST
    body_format: json
    body: '{"content": "Reboot required on {{ inventory_hostname }}"}'
    headers:
      Content-Type: application/json
    status_code: 204
  when: reboot_required.stat.exists