---
- name: "Update hosts"
  hosts: "{{ hosts | default([]) }}"
  remote_user: ansible
  tasks:
    - name: Import update role
      ansible.builtin.import_role:
        name: update
      tags:
        - update
